name: Publish Python Package
on:
  release:
    types:
      - published
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install --no-interaction
      - name: publish to pypi
        env:
          TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry publish --build --username __token__ --password $TOKEN
